### ISSUE TITLE
Shortcut for screenshots

### ISSUE THREAD

**Issue by sndpl** [pokebyte/CocoaMSX#20]
At the moment you need to go to the File menu and choose screenshot, this isn't easy (user friendly) if you need to take multiple screenshots.

It would be nice if there is a shortcut that takes the screenshot and saves it automatically with a predefined name, like cocoamsx_screenshot_0000.png for example and increase the numbering by checking the last saved screenshot in the save dir.

Maybe create a setting for the save dir of screenshots.

**Comment by sndpl** [comment]
:+1:

**Comment by pokebyte** [comment]
:beer: !

**Comment by sndpl** [comment]
When you visit The Netherlands, I will buy you one ;)

**Comment by pokebyte** [comment]
:) deal
