### ISSUE TITLE
Blurry image when fullscreen on retina displays

### ISSUE THREAD

**Issue by kerunaru** [pokebyte/CocoaMSX#27]
When fullscreen mode, image seem blurry.
Maybe a resizing instead of redrawing at the current resolution?

I have no filter applied, btw…

![captura de pantalla 2014-11-17 a las 20 02 21](https://cloud.githubusercontent.com/assets/94023/5075638/bab0bc76-6e94-11e4-8974-ef1b744866a4.png)

**Comment by kerunaru** [comment]
Well… Just for your information, this is still an issue on 1.43ß

**Comment by pokebyte** [comment]
Thanks for letting me know.

**Comment by pokebyte** [comment]
So looks like it has to do with how `NSOpenGLView` deals with drawing to the retina display:
https://developer.apple.com/library/mac/documentation/GraphicsAnimation/Conceptual/HighResolutionOSX/CapturingScreenContents/CapturingScreenContents.html

After some futzing, here's what I have:
<img width="816" alt="retina ready" src="https://cloud.githubusercontent.com/assets/2538706/10780701/a14089ce-7cfd-11e5-8fcd-86f753e14dc1.png">

It's marginally better than the current situation, see here:

<img width="388" alt="screen shot 2015-10-27 at 22 50 31" src="https://cloud.githubusercontent.com/assets/2538706/10780709/bf75fc8a-7cfd-11e5-94af-c02ae1f4ba64.png">

(current at top, new at bottom)

especially with regard to things like text, but still not as nice as on a plain display. Two options are 

a) use `GL_NEAREST` for the screen textures - this doesn't scale well unless handled properly, and requires "stepping" in fixed pixel increments to avoid scaling artifacts
b) prescale the screen bitmap - this may (will, in all likelihood) negatively impact performance

Those two are probably beyond this particular issue, and may need to be addressed separately. I will probably publish another beta release soon, which will also address #31, so you should be able to see what it looks like - hopefully it will improve the situation somewhat. I'll add a comment here when that happens.

**Comment by kerunaru** [comment]
Aww… Sorry to say this but I compiled the last version of the code and right now it's blurry windowed and in fullscreen.

Before:
<img width="628" alt="captura de pantalla 2015-10-28 a las 7 42 03" src="https://cloud.githubusercontent.com/assets/94023/10781465/9a8d5bda-7d47-11e5-8bdd-ee88b19cd1e3.png">

Now:
<img width="656" alt="captura de pantalla 2015-10-28 a las 7 42 08" src="https://cloud.githubusercontent.com/assets/94023/10781468/a3529dc0-7d47-11e5-9100-c16798e271c9.png">

**Comment by pokebyte** [comment]
Yep, and that's pretty consistent with what the Apple article talks about. To replicate the look of the non-retina screen on retina, I'd have to render the MSX screen at 4x magnification.

**Comment by pokebyte** [comment]
Since blueMSX's renderer only supports 1x and 2x zoom, the `VideoRender.c` needs to be updated.

**Comment by pokebyte** [comment]
I've uploaded [a new beta version](http://cocoamsx.com/CocoaMSX-1.43beta3.zip) - please give it a try. Instead of adding support in the core, I'm addressing retina support by adding an extra post-rendering pass through a scaler. Since I don't have an actual retina display to test with, I'd be curious to know how it looks - please let me know.

**Comment by kerunaru** [comment]
Ooops… Okay so, now the pixel are sharp. That's fine, but…

Windowed on start
<img width="656" alt="captura de pantalla 2015-10-31 a las 10 42 18" src="https://cloud.githubusercontent.com/assets/94023/10862925/a66c9f8e-7fbc-11e5-9ddc-0720578cc3a5.png">

On fullscreen
<img width="1020" alt="captura de pantalla 2015-10-31 a las 10 44 02" src="https://cloud.githubusercontent.com/assets/94023/10862926/aa497e42-7fbc-11e5-9fbd-53a3e822d058.png">

Windowed after exit fullscreen
<img width="656" alt="captura de pantalla 2015-10-31 a las 10 44 09" src="https://cloud.githubusercontent.com/assets/94023/10862927/adef1d04-7fbc-11e5-94ad-5d75d0379c81.png">

**Comment by pokebyte** [comment]
That's odd; now I'm seeing that as well. I'll take a look.

The messages are caused by the window resize animations. You're seeing them now, because the build is a debug build. They're suppressed in release builds.

**Comment by pokebyte** [comment]
Sorry about that - I introduced bugs when I added compatibility checks. I've updated the file (same one) - please give it another try.

**Comment by kerunaru** [comment]
Take it easy! :smile: 

Now it seems great on windowed mode

<img width="656" alt="captura de pantalla 2015-10-31 a las 17 27 44" src="https://cloud.githubusercontent.com/assets/94023/10864634/d6174454-7ff4-11e5-825c-663d401dc8a0.png">

But it's still blurry in fullscreen mode (as the origin of this issue :sob: )

<img width="1020" alt="captura de pantalla 2015-10-31 a las 17 27 48" src="https://cloud.githubusercontent.com/assets/94023/10864638/f7f12612-7ff4-11e5-8ef9-8460a9a594bb.png">

**Comment by pokebyte** [comment]
In that case, it's not really the retina that's the issue - it's the fact that scaling the screen beyond its original 4x (2x on non-retina screens) size creates anti-aliasing effects. The alternative is using `GL_NEAREST` for the `GL_TEXTURE_MAG_FILTER` parameter, but that would look horrible if the user attempted to resize the window. What you're observing would happen on any screen (retina and plain), and has more to do with the difference between the original size and the full screen size than anything else.

Best way to address this is to switch to `GL_NEAREST` in full screen mode, and restrict the size of `NSOpenGLView` to the nearest 4-pixel multiple. That would be something beyond this particular issue - it's less a bug and more a feature request. As of now, full screen appearance is identical between retina/non-retina screens.

Feel free to create an additional ticket, and I'll do my best to target it for the next release.

**Comment by kerunaru** [comment]
Ok, I'm going to create a new ticket with the feature request… And you're welcome! :+1:
