### ISSUE TITLE
Unable to load CAS files

### ISSUE THREAD

**Issue by Paneque** [pokebyte/CocoaMSX#28]
Good afternoon,
I have problems when loading CAS files as the "Insert" options is not enabled in cassette mode. Should I make some configuration changes?
Thanks in advance.

**Comment by pokebyte** [comment]
Which system are you using? C-BIOS systems are unable to load cassettes or disks. Try another (e.g. Sony HB-F1XD)

**Comment by Paneque** [comment]
Thanks a lot! Yes, I was trying with C-BIOS. I have just changed it and the option is now enabled.
Thanks again!

**Comment by pokebyte** [comment]
No problem
