### ISSUE TITLE
Loading tape  files doesn't work

### ISSUE THREAD

**Issue by sndpl** [pokebyte/CocoaMSX#34]
When I insert a .cas file and type RUN"CAS:" nothing is found (in the latest beta version). The same files does work in openMSX.

The file i'm using can be downloaded from http://www.filedropper.com/rataplan  (it was the first free file sharing site i found, so i hope it works).

**Comment by pokebyte** [comment]
Hmm, can't find the file. Can you please email it to me?

**Comment by sndpl** [comment]
Little bit late, but you can download the file here: http://www.generation-msx.nl/upload/hyperspace.zip

**Comment by pokebyte** [comment]
Cool, thank you

**Comment by pokebyte** [comment]
OK, so I was able to get it to run after switching to a different machine (MSX2 - Japanese). Could this be a loader issue? I'm observing the same behavior in blueMSX.

**Comment by sndpl** [comment]
I used a Philips NMS8250, and on openMSX it works with the same configuration. Also it's a european (italian) game.

Will try some other machines tonight.

**Comment by pokebyte** [comment]
Indeed, the game doesn't seem to work with any of the 3 NMS8250 machines - both in CocoaMSX and blueMSX. Looks like an issue with the emulation core.

**Comment by mars2000you** [comment]
It's not a bug with the emulation core.

In blueMSX, only the generic machines have the CAS patch applied on the BIOS rom to allow direct loading of CAS files. If an user wants to load CAS files when running a specific machine, he needs first to edit this machine in the Machine editor. This choice was made for eventual later WAV support.

As CocaMSX uses the blueMSX machines, the behaviour is the same. As CocoaMSX does not have yet a Machine editor, the user needs to modify directly the config.ini file of the specific machine.

Example with the Toshiba HX-10 machine (you need to replace 20 by 66 for the rom type of the BIOS rom)

Before change :

[code][Slots]
0 0 0 0 84 "" ""
0 0 0 4 20 "Machines/MSX - Toshiba HX-10/hx10bios.rom" ""
2 0 0 8 23 "" ""[/code]

After change :

[code][Slots]
0 0 0 0 84 "" ""
0 0 0 4 66 "Machines/MSX - Toshiba HX-10/hx10bios.rom" ""
2 0 0 8 23 "" ""[/code]

**Comment by pokebyte** [comment]
Thank you for the explanation (I also saw your comment at the msx.org forum). I'll look into this further.
