### ISSUE TITLE
Proper icon

### ISSUE THREAD

**Issue by pokebyte** [pokebyte/CocoaMSX#39]
A proper application icon is needed.

**Comment by sndpl** [comment]
I'm not a designer, so this is the best I could make :)

![cocoamsxlogo](https://cloud.githubusercontent.com/assets/363211/15992279/66d48bfc-30c9-11e6-9c40-d32ce9f381ae.png)

**Comment by pokebyte** [comment]
Thank you! I love the disc in the back, the inset and the MSX logo. But I'd like to exclude any explicit references to games. Machine-specific references would be cool, or something related to the cacao plant and/or its color theme.

**Comment by sndpl** [comment]
Ok, second attempt with a cocoa tree. Any examples of Machine specific references you would like to see?
![cocoamsxlogo_v2](https://cloud.githubusercontent.com/assets/363211/15993909/a844ffba-30f4-11e6-9a1f-056d3085941b.png)

**Comment by pokebyte** [comment]
Actually, this looks great. Can you simplify the drop shadow a bit? Reduce the length vertically, and have it so that it's visible all around just barely, but a little more pronounced in +y direction? Here's an example using the Atom logo:

![screen shot 2016-06-12 at 20 59 52](https://cloud.githubusercontent.com/assets/2538706/15996805/d370929e-30e0-11e6-84f3-d1f24c98276f.png)

**Comment by pokebyte** [comment]
I decided to fiddle around with Inkscape for a bit and came up with this:

![g5217](https://cloud.githubusercontent.com/assets/2538706/16361458/b436d94a-3b46-11e6-8d0f-d9ecdf9be7f4.png)

It's a cross-section of a cacao pod, roughly based on this:

https://upload.wikimedia.org/wikipedia/commons/0/01/Cacao-pod-k4636-14.jpg

I tried to follow Material design guidelines as much as my limited knowledge of design principles allows - I'd be curious to know what you think.

**Comment by pokebyte** [comment]
I ended up going with this:

![icon_512x512](https://cloud.githubusercontent.com/assets/2538706/16403465/54dd1148-3caa-11e6-911d-8f3438a9e2ff.png)

I'm not super-content with it, but it'll have to do for now. The shape is reminiscent of a cacao pod, there's an MSX logo, and the colors are all from the MSX1 palette (although the blue has a slight vertical gradient). So conceptually, it has both cocoa and MSX parts :)

Thanks for motivating me to get working. As a thank you note, take a look at the About screen when the next release comes out. ;)

**Comment by sndpl** [comment]
Sorry, was a little bit busy the last days, but nice logo :)
